name: Rust CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust stable
        run: rustup update stable

      - name: Run cargo test
        run: cargo test --verbose
